### ISSUE TITLE
The '(' and ')' is not being translated right.

### ISSUE THREAD

**Issue by harrrrshit** [CrazyFlyKite/MorseCodePy#2]
from MorseCodePy import encode
text = input("Enter the line you want to translate in Morse Code: ")
morsecodedTEXT = (encode(text,language='english'))
print(morsecodedTEXT)

I wrote the code and then entered "(" as the input, it outputs "*" which is the wrong translation

**Comment by CrazyFlyKite** [comment]
"*"

**Comment by CrazyFlyKite** [comment]
"**\***" means that symbol doesn't have any translations. So MorseCodePy automatically translates it to "**\***".

Thanks for the feedback!

**Note**: You can modify error output by specifying parameter error
encode('Hello', language='english', error='#')
